- add core UI SearchControllers
liilkaz/PodcastApp pull request #13
Opened 2023-10-02 20:06 UTC by AnnaZaitsava

- added core UI SearchController
- added core UI SearchResultController
- added additional fonts

2023-10-02 20:29 UTC, liilkaz requested changes
желательно подправить недочеты.
и удалить лишние пробелы, их очень много. 
допустимо между строчками не больше одного

2023-10-02 20:29 UTC, liilkaz commented on PodcastApp/Extensions/UIFont + Extension.swift
> +
в девелопе уже есть методы для шрифтов:
```
 static func regular14() -> UIFont? {
        return UIFont(name: "Manrope-Regular", size: 14)
    }
    
    static func extraLight() -> UIFont? {
        return UIFont(name: "Manrope-ExtraLight", size: 16)
    }
    
    static func semiBold() -> UIFont? {
        return UIFont(name: "Manrope-SemiBold", size: 16)
    }
```

2023-10-02 20:29 UTC, liilkaz commented on PodcastApp/Search/GenresHardData.swift
> +}
жанры тоже вроде есть, но пока пусть будут

2023-10-02 20:29 UTC, liilkaz commented on PodcastApp/Search/SearchGenres/Cells/GenreCell.swift
> +        return image
в чем отличие от BrowseCell? если разницы нет - переиспользуй одну ячейку

2023-10-02 20:29 UTC, liilkaz commented on PodcastApp/Search/SearchGenres/SearchViewController.swift
> +        default: break
откуда эти значения?

2023-10-05 20:38 UTC, fullzoom59 approved these changes

2023-10-07 17:26 UTC, closed without merging